# Данные и методология

```{r include=FALSE}
pacman::p_load(tidyverse, kableExtra, here, e1071, stats, tseries, pracma, broom, readxl)
main <- read_xlsx(here("data", "main1.xlsx"))
```

## Анализ данных

{Таблица 1:} Переменные, используемые в процессе прогнозирования

```{r include=FALSE}
table_one <- 
  tribble(
  ~ Variable, ~ Descripción, ~ Fuente,
  "ipc", "Темпы изменения индекса потребительских цен в месячном исчислении", "Росстат",
  "agro_price", "Темпы изменения индекса цен сельхозпроизводителей в месячном исчислении", "Росстат",
  "deposit", "Темпы изменения объема депозитов населения в в месячном исчислении", "Банк России",
  "demand", "Темпы изменения оборота розничной торговли в месячном ислчислении", "Росстат",
  "usd_cb", "Темпы изменения курса доллара в месячном исчислении", "Банк России"
  )
```

```{r table_one, echo=FALSE}
kbl(table_one, 
    booktabs = T, 
    align = c("clc")) %>%
  kable_styling(font_size = 9,
                full_width = T) %>% 
  row_spec(0, 
           bold = TRUE, 
           extra_css = 'vertical-align: middle !important;') %>% 
  column_spec(1, width = "1.7cm") %>% 
  column_spec(2, width = "12cm") %>% 
  group_rows(start_row = 1, 
             end_row = 5, 
             latex_gap_space = "-0.50cm")
```

\textbf{Рисунок 1:} Целевая переменная и выбранные предикторы

```{r include=FALSE}
order <- table_one %>% rowid_to_column(var = "id") %>% select(id, "name" = Variable)

fig1 <- 
  main %>% 
  pivot_longer(-date) %>% 
  arrange(name, date) %>% 
  left_join(order) %>% 
  mutate(name = as_factor(name)) %>% 
  group_by(name)
```

```{r fig_one, echo=FALSE, fig.align = 'center', fig.dim = c(11.5, 4.7)}
fig1 %>% 
  ggplot() +
  geom_line(aes(x = date, y = value, color = fct_reorder(name, id))) + 
  scale_y_continuous(limits = c(-20, 20)) +
  theme_bw() +
  theme(
        # X axis
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 12, color = "black"),
        # Y axis
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 12, color = "black"),
        # Panel
        panel.grid = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.background = element_rect(fill = "white", color = "black"),
        # Legend
        legend.title = element_blank(),
        legend.text = element_text(size = 11),
        legend.position = "bottom",
        legend.justification = "center",
        legend.margin = margin(.5, 0, 0, 0, "cm")
    ) + 
    guides(colour = guide_legend(nrow = 1))
```
